import { Button, Palette, VerticalBox } from "std-widgets.slint";

export component ConfirmationOverlay inherits Rectangle {
    in property <string> message;
    property <string> prompt;
    property <bool> active: false;
    property <string> confirm-text: @tr("Yes");
    property <string> cancel-text: @tr("No");
    callback on-confirm;
    callback on-cancel;

    public function show() {
        active = true;
    }

    if active: Rectangle {
        visible: true;
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        background: black.transparentize(20%);
        TouchArea {
            HorizontalLayout {
                alignment: center;
                VerticalLayout {
                    alignment: center;
                    Rectangle {
                        width: 400px;
                        preferred-height: 0;
                        drop-shadow-color: black;
                        drop-shadow-blur: 12px;
                        border-radius: 8px;
                        background: Palette.background.brighter(20%);
                        VerticalBox {
                            alignment: center;
                            padding: 16px;
                            spacing: 16px;
                            message-text := Text {
                                text: prompt;
                            }

                            HorizontalLayout {
                                Rectangle { }

                                Button {
                                    text: confirm-text;
                                    primary: true;
                                    clicked => {on-confirm();}
                                }
                                Button {
                                    text: cancel-text;
                                    clicked => {on-cancel();}
                                }

                                Rectangle { }
                            }
                        }
                    }
                }
            }
        }
    }
}
