import { Button, Palette, VerticalBox } from "std-widgets.slint";

export component MessageOverlay inherits Rectangle {
    in-out property <string> message;
    in-out property <bool> active: false;
    if active: Rectangle {
        visible: true;
        x: 0;
        y: 0;
        width: 100%;
        height: 100%;
        background: black.transparentize(20%);
        TouchArea {
            HorizontalLayout {
                alignment: center;
                VerticalLayout {
                    alignment: center;
                    Rectangle {
                        width: 400px;
                        preferred-height: 0;
                        drop-shadow-color: black;
                        drop-shadow-blur: 12px;
                        border-radius: 8px;
                        background: Palette.background.brighter(20%);
                        VerticalBox {
                            alignment: center;
                            padding: 16px;
                            spacing: 16px;

                            message-text := Text {
                                text: message;
                                wrap: TextWrap.word-wrap;
                            }

                            HorizontalLayout {
                                Rectangle { }

                                Button {
                                    text: @tr("Dismiss");
                                    clicked => {
                                        active = false;
                                    }
                                }

                                Rectangle { }
                            }
                        }
                    }
                }
            }
        }
    }
}
