[package]
name = "smudgy"
version = "0.0.1"
authors = ["Walter Kalata <ping@walter.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
confy = "0.4.0"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.5.0", features = ["full"] }
tokio-util = { version = "0.6.6", features = ["codec"]}
tokio-stream = "0.1.5"
futures = { version = "0.3.0"}