// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Button, GroupBox, SpinBox, ComboBox, CheckBox, LineEdit, TabWidget, VerticalBox, HorizontalBox,
    Slider, ProgressIndicator, SpinBox, Switch, Spinner, GridBox, Palette } from "std-widgets.slint";
import { Page } from "./page.slint";
import { Profile, UiResult } from "./types.slint";
import { MessageOverlay } from "../components/message_overlay.slint";

export component CreateProfilePage inherits Page {
    title: @tr("Create Profile");
    callback create-profile(Profile) -> UiResult;
    property <Profile> profile;
    property <UiResult> result;
    Rectangle {
        GroupBox {
            vertical-stretch: 0;
            title: @tr("Details");
            VerticalLayout {
                padding: 0px;
                HorizontalBox {
                    alignment: start;
                    VerticalBox {
                        VerticalBox {
                            Text {
                                text: @tr("Name");
                            }

                            name-input := LineEdit {
                                placeholder-text: @tr("The name of the profile, e.g. SmudgyMUD");
                            }
                        }

                        HorizontalLayout {
                            VerticalBox {
                                width: 200px;
                                Text {
                                    text: @tr("Host");
                                }

                                host-input := LineEdit {
                                    placeholder-text: "e.g. mud.example.com";
                                }
                            }

                            VerticalBox {
                                Text {
                                    text: @tr("Port");
                                }

                                port-input := LineEdit {
                                    input-type: number;
                                }
                            }
                        }

                        Button {
                            text: @tr("Create");
                            clicked => {
                                result = create-profile({ name: name-input.text, host: host-input.text, port: port-input.text.to-float() });
                                if (!result.success) {
                                    message-box.active = true;
                                }
                            }
                        }
                    }
                }
            }
        }
    
        message-box := MessageOverlay {
            message: result.message;
        }
        
    }
}
