// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Switch, GridBox, ListView, ScrollView, HorizontalBox, VerticalBox, Palette } from "std-widgets.slint";

export component Page inherits VerticalBox {
    in property<string> title: "title";
    in property<string> description: "description";
    in property<bool> show-enable-switch: true;

    HorizontalBox {
        Text {
            font-size: 24px;
            text <=> root.title;
        }
    }

    @children
}