export global SmudgyState {
    in-out property <bool> is-full-screen;
}

export global HeroIconsOutline {
    out property <image> arrow-path: @image-url("../assets/heroicons/optimized/24/outline/arrow-path.svg");
    out property <image> arrows-pointing-in: @image-url("../assets/heroicons/optimized/24/outline/arrows-pointing-in.svg");
    out property <image> arrows-pointing-out: @image-url("../assets/heroicons/optimized/24/outline/arrows-pointing-out.svg");
    out property <image> bars-3: @image-url("../assets/heroicons/optimized/24/outline/bars-3.svg");
    out property <image> ellipsis-horizontal: @image-url("../assets/heroicons/optimized/24/outline/ellipsis-horizontal.svg");
    out property <image> ellipsis-vertical: @image-url("../assets/heroicons/optimized/24/outline/ellipsis-vertical.svg");
    out property <image> eye: @image-url("../assets/heroicons/optimized/24/outline/eye.svg");
    out property <image> eye-slash: @image-url("../assets/heroicons/optimized/24/outline/eye-slash.svg");
    out property <image> plus: @image-url("../assets/heroicons/optimized/24/outline/plus.svg");
    out property <image> trash: @image-url("../assets/heroicons/optimized/24/outline/trash.svg");
    out property <image> x-circle: @image-url("../assets/heroicons/optimized/24/outline/x-circle.svg");
    out property <image> x-mark: @image-url("../assets/heroicons/optimized/24/outline/x-mark.svg");
}

export global Palette {
    in-out property <color> background: #111111;

    in-out property <color> surface-l-100: #0a060f;
    in-out property <color> surface-l-800: #0d0919.darker(50%);
    in-out property <color> surface-r-100: #1c0000;
    in-out property <color> surface-r-800: #1c0000.darker(50%);
    in-out property <color> toolbar-sep-l: #b380ff;
    in-out property <color> toolbar-sep-r: #ff00001a;

    in-out property <brush> toolbar-background: @linear-gradient(90deg, surface-l-100 0%, surface-r-100 100%);
    in-out property <brush> toolbar-border: @linear-gradient(90deg, toolbar-sep-l 0%, toolbar-sep-r 100%);
    in-out property <brush> toolbar-cover: @linear-gradient(90deg, surface-l-800 0%, surface-r-800 100%);
    
    in-out property <color> button-primary-bg: white;
    in-out property <color> button-primary-color: #150b22;
    in-out property <color> button-secondary-bg: #150b22;
    in-out property <color> button-secondary-color: #b380ff;
}

export struct AutocompleteResult {
    success: bool,
    new-line: string,
    autocompleted-start: int,
    autocompleted-end: int
}
export struct SessionState {
    name: string,
    buffer: [image],
    scrollback_size: [int],
}

export struct TerminalSizeHints {
    editor-area-height: physical-length,
    terminal-padding: physical-length,
    terminal-spacing: physical-length,
    terminal-scrollbar-width: physical-length
}

export enum SessionKeyPressResponseType {accept, reject, replace-input}

export struct SessionKeyPressResponse {
    response: SessionKeyPressResponseType,
    str_args: [string],
    int_args: [int]
}